config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'public/users/registrations',
   sessions: 'public/users/sessions'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :password], controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'inquiries#index'
    resources :users, only: [:index, :show, :edit, :update, :withdraw]
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :inquiries, only: [:index, :show, :update]
    resources :groups, only: [:index, :show, :destroy]
    resources :programs, except: :show
    resources :categories, except: :show
    get '/searches' => 'searches#search', as: "searches"
  end

  scope module: :public do
    devise_scope :user do
      post 'guest_login', to: 'users/sessions#guest_login'
    end
    resources :users, only: [:edit, :update, :show]
    get '/mypage' => 'users#mypage', as: "mypage"
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts do
      resources :comments, only: [:create, :show, :destroy]
    end
    resources :inquiries, only: [:new, :create]
    get 'inquiries/thanks' => 'inquiries#thanks', as: "thanks"
    resources :groups, except: :destroy do
      resource :user_group_combinations, only: [:create, :destroy]
    end
    resources :user_group_combinations, only: [:update]
    resources :programs, only: [:index, :show]
    get '/search' => 'searches#search', as: "search"
  end

  root to: "homes#home"
  get '/about' => 'homes#about', as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: :true

  def self.search_for(content, method)
    if method == 'perfect'
      Comment.where(body: content)
    elsif method == 'forward'
      Comment.where('body Like ?', content + '%')
    elsif method == 'backword'
      Comment.where('body Like ?', '%' + content)
    else
      Comment.where('body Like ?', '%' + content + '%')
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'
  
  def index
    @comments = Comment.page(params[:comments_page]).per(6)
    @total_comments_count = Comment.all.count
  end

  def show
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    flash[:notice] = "削除しました"
    redirect_to admin_comments_path
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_index.html.erb
<div class="d-flex justify-content-end mb-1">
  <%= paginate comments, param_name: 'comments_page' %>
</div>
<table class="table table-hover">
  <thead>
    <tr style="background-color: rgba(165, 143, 134, 0.2);">
      <th>コメント者</th>
      <th>コメント</th>
      <th>コメント日</th>
      <th>コメントした投稿</th>
      <th col="1"> </th>
    </tr>
  </thead>
  <tbody>
    <% comments.each do |comment| %>
      <tr>
        <td>
          <%= link_to comment.user.name, admin_user_path(comment.user) %>
        </td>
        <td class="text-truncate" style="max-width: 150px">
          <%= link_to comment.body, admin_comment_path(comment) %>
        </td>
        <td>
          <%= comment.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= link_to comment.post.title, admin_post_path(comment.post) %>
        </td>
        <td>
          <%= link_to '削除', admin_comment_path(comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-dark py-1" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-end mt-1">
  <%= paginate comments, param_name: 'comments_page' %>
</div>

app/views/admin/comments/index.html.erb
<h1>コメント一覧</h1>
  <div class="d-flex justify-content-end mb-1">
    ｜全 <%= @total_comments_count %> 件｜
    <%= paginate @comments, param_name: 'comments_page' %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr style="background-color: rgba(165, 143, 134, 0.2);">
        <th>コメント者</th>
        <th>コメント</th>
        <th>コメント日</th>
        <th>コメントした投稿</th>
        <th col="1"> </th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td>
            <%= link_to comment.user.name, admin_user_path(comment.user) %>
          </td>
          <td class="text-truncate" style="max-width: 150px">
            <%= link_to comment.body, admin_comment_path(comment) %>
          </td>
          <td>
            <%= comment.created_at.strftime('%Y/%m/%d') %>
          </td>
          <td>
            <%= link_to comment.post.title, admin_post_path(comment.post) %>
          </td>
          <td>
            <%= link_to '削除', admin_comment_path(comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-dark py-1" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-end mt-1">
    <%= paginate @comments, param_name: 'comments_page' %>
  </div>

app/views/admin/comments/show.html.erb
<h1>コメント詳細</h1>
<div class="text-right mb-3">
  <%= link_to '削除', admin_comment_path(@comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-dark" %>
  <%= link_to '戻る', admin_comments_path, class: "btn btn-secondary" %>
</div>
<div class="row">
  <div class="col-lg-6">
    <p class="py-3 pl-1" style="background-color: rgba(165, 143, 134, 0.2);">
      <strong>コメント詳細</strong>
    </p>
    <p>
      コメント者：
      <%= @comment.user.name %>
    </p>
    <p class="wrap-text">
      ◆ コメント内容 ◆<br>
      <%= simple_format @comment.body %>
    </p>
    <p>
      コメント日：
      <%= @comment.created_at.strftime('%Y/%m/%d') %>
    </p>
    <p>
      同投稿に対するコメント数：
      <%= @post.comments.count %> 件
    </p>
  </div>
  <div class="col-lg-6">
    <p class="py-3 pl-1" style="background-color: rgba(165, 143, 134, 0.2);">
      <strong>コメントした投稿</strong>
    </p>
    <p>
      タイトル：
      <%= link_to @post.title, admin_post_path(@post) %>
    </p>
    <p>
      投稿者：
      <%= link_to @post.user.name, admin_user_path(@post.user) %>
    </p>
    <p class="wrap-text">
      ◆ 投稿内容 ◆<br>
      <%= simple_format @post.body %>
    </p>
    <p>
      投稿日：
      <%= @post.created_at.strftime('%Y/%m/%d') %>
    </p>
    <p>
      投稿更新日：
      <%= @post.updated_at.strftime('%Y/%m/%d') %>
    </p>
  </div>
</div>