config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'public/users/registrations',
   sessions: 'public/users/sessions'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :password], controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'inquiries#index'
    resources :users, only: [:index, :show, :edit, :update, :withdraw]
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :inquiries, only: [:index, :show, :update]
    resources :groups, only: [:index, :show, :destroy]
    resources :programs, except: :show
    resources :categories, except: :show
    get '/searches' => 'searches#search', as: "searches"
  end

  scope module: :public do
    devise_scope :user do
      post 'guest_login', to: 'users/sessions#guest_login'
    end
    resources :users, only: [:edit, :update, :show]
    get '/mypage' => 'users#mypage', as: "mypage"
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts do
      resources :comments, only: [:create, :show, :destroy]
    end
    resources :inquiries, only: [:new, :create]
    get 'inquiries/thanks' => 'inquiries#thanks', as: "thanks"
    resources :groups, except: :destroy do
      resource :user_group_combinations, only: [:create, :destroy]
    end
    resources :user_group_combinations, only: [:update]
    resources :programs, only: [:index, :show]
    get '/search' => 'searches#search', as: "search"
  end

  root to: "homes#home"
  get '/about' => 'homes#about', as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  scope :publidhed, -> { where(publish_status: "published") }
  has_one_attached :image

  belongs_to :admin
  belongs_to :category

  enum publish_status: { draft: 0, published: 1, non_public: 2 }

  validates :title, presence: true
  validates :body, presence: true
  validates :start_time, presence: true
  validates :price, presence: true
  validates :time_required, presence: true
  validates :publish_status, presence: true
  validates :category_id, presence: true

  def get_image_resize(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0").processed
  end

  def get_image
   unless image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
   end
   image.variant(resize_to_limit: [600, 600]).processed
  end

  def start_date
    start_time&.to_date
  end

  def start_date=(date)
    if date.present?
      date = Date.parse(date) if date.is_a?(String)
      if start_time.present?
        self.start_time = start_time.change(year: date.year, month: date.month, day: date.day)
      else
        self.start_time = date.to_time
      end
    end
  end

  def start_time_only
    return nil unless start_time.present?
    
    time_obj = start_time.is_a?(String) ? Time.parse(start_time) : start_time
    time_obj.change(year: 2000, month: 1, day: 1)
  end

  def start_time_only=(time)
    if time.present?
      hour, minute = time.split(":").map(&:to_i)
      if start_time.present?
        self.start_time = start_time.change(hour: hour, min: minute)
      else
        self.start_time = Time.current.change(hour: hour, min: minute)
      end
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Program.where(title: content)
    elsif method == 'forward'
      Program.where('title Like ?', content + '%')
    elsif method == 'backword'
      Program.where('title Like ?', '%' + content)
    else
      Program.where('title Like ?', '%' + content + '%')
    end
  end
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < ApplicationController
  layout 'admin'
  
  def new
    @program = Program.new
  end

  def create
    @program = current_admin.programs.build(program_params)
    if params[:body].present?
      @program.body = params[:body].gsub(/\R/, "<br>")
    end
    if @program.save
      @program.image.attach(params[:program][:image])
      flash[:notice] = "作成しました"
      redirect_to edit_admin_program_path(@program)
    else
      flash.now[:danger] = "作成に失敗しました"
      render :new
    end
  end

  def index
    @programs = Program.page(params[:programs_page]).per(6)
    @total_programs_count = Program.all.count
  end

  def edit
    @program = Program.find(params[:id])
  end

  def update
    @program = Program.find(params[:id])
    if params[:body].present?
      @program.body = params[:body].gsub(/\R/, "<br>")
    end
    if @program.update(program_params)
      flash[:notice] = "変更を保存しました"
      redirect_to edit_admin_program_path(@program)
    else
      flash.now[:notice] = "変更の保存に失敗しました"
      render :edit
    end
  end

  def destroy
    program = Program.find(params[:id])
    program.destroy
    flash[:notice] = "削除しました"
    redirect_to admin_programs_path
  end

  private

  def program_params
    params.require(:program).permit(:image, :title, :body, :start_date, :start_time_only, :publish_status, :time_required, :price, :category_id)
  end
end

app/helpers/admin/programs_helper.rb
module Admin::ProgramsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/admin/programs/_form.html.erb
<%= form_with model: [:admin, program] do |f| %>
  <div class="row">
    <div class="col-lg-8">
      <%= render 'layouts/error_messages', model: f.object %>
      <div id="image-preview" class="mb-3">
        <%= image_tag program.get_image, size: "300x240" unless program.new_record? %><br>
      </div>
      <%= f.label :image, "画像" %>
      <%= f.file_field :image, accept: "image/*", class: "mb-3", id: 'image-upload' %><br>

      <%= f.label :title, "講座名" %><br>
      <%= f.text_field :title, class: "form-control" %>
      
      <%= f.label :body, "紹介文" %><br>
      <%= f.text_area :body, class: "form-control" %>

      <%= f.label :start_date, "開催日" %><br>
      <%= f.date_field :start_date, class: "form-control" %>

      <%= f.label :start_time_only, "時間" %><br>
      <%= f.time_field :start_time_only, class: "form-control" %>
      
      <%= f.label :time_required, "所要時間" %><br>
      <%= f.text_field :time_required, class: "form-control" %>

      <%= f.label :price, "参加費" %><br>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="col-lg-4 px-lg-4">
      <%= f.label :category_id, "カテゴリー" %><br>
      <%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: "--選択してください--" }, { class: "form-control" } %>

      <%= f.label :publish_status, "公開ステータス" %><br>
      <%= f.select :publish_status, Program.publish_statuses.keys.map { |status| [I18n.t("enums.program.publish_status.#{status}"), status] } %>

      <div class="text-right mr-3 mt-3">
        <%= render 'submit_button', f: f, submit_label: submit_label %>
      </div>
    </div>
  </div>
<% end %>

<script>
document.getElementById('image-upload').onchange = function(e) {
  var file = e.target.files[0];
  var reader = new FileReader();

  reader.onload = function(event) {
    var img = document.createElement('img');
    img.src = event.target.result;
    const preview = document.getElementById('image-preview')
    preview.innerHTML = "";
    preview.appendChild(img);
    const image = document.querySelector("#image-preview img")
    image.setAttribute('width', '300')
    image.setAttribute('height', '240')
  };

  reader.readAsDataURL(file);
};
</script>

app/views/admin/programs/_index.html.erb
<div class="d-flex justify-content-end mb-1">
  <%= paginate programs, param_name: 'programs_page' %>
</div>
<table class="table table-hover">
  <thead>
    <tr style="background-color: rgba(165, 143, 134, 0.2);">
      <th>ステータス</th>
      <th>画像</th>
      <th>タイトル</th>
      <th>カテゴリー</th>
      <th>開催日時</th>
      <th>作成日時</th>
    </tr>
  </thead>
  <tbody>
    <% programs.each do |program| %>
      <tr>
        <td>
          <%= "#{I18n.t("enums.program.publish_status.#{program.publish_status}")}" %>
        </td>
        <td>
          <%= image_tag program.get_image, size: "100x80" %>
        </td>
        <td>
          <%= link_to edit_admin_program_path(program) do %>
            <%= program.title %>
          <% end %>
        </td>
        <td>
          <%= program.category.name %>
        </td>
        <td>
          <%= program.start_time.strftime("%Y/%m/%d %H:%M") %>
        </td>
        <td>
          <%= program.created_at.strftime("%Y/%m/%d") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-end mb-1">
  <%= paginate programs, param_name: 'programs_page' %>
</div>

app/views/admin/programs/_submit_button.html.erb
<%= f.submit submit_label, class: "btn btn-secondary" %>

app/views/admin/programs/edit.html.erb
<h1>講座編集</h1>
<div class="mb-3 mr-3 text-right">
  <%= link_to '削除', admin_program_path(@program), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-dark" %>
  <%= link_to '戻る', admin_programs_path, class: "btn btn-secondary" %>
</div>

<% submit_label = "更新" %>
<%= render 'form', program: @program, submit_label: submit_label %>

app/views/admin/programs/index.html.erb
<h1>講座一覧</h1>
  <div class="mb-3 mr-3 text-right">
    <%= link_to '新規作成', new_admin_program_path, class: "btn btn-secondary" %>
  </div>
  <div class="d-flex justify-content-end mb-1">
    ｜全 <%= @total_programs_count %> 件｜
    <%= paginate @programs, param_name: 'programs_page' %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr style="background-color: rgba(165, 143, 134, 0.2);">
        <th>ステータス</th>
        <th>画像</th>
        <th>タイトル</th>
        <th>カテゴリー</th>
        <th>開催日時</th>
        <th>作成日時</th>
      </tr>
    </thead>
    <tbody>
      <% @programs.each do |program| %>
        <tr>
          <td>
            <%= "#{I18n.t("enums.program.publish_status.#{program.publish_status}")}" %>
          </td>
          <td>
            <%= image_tag program.get_image, size: "100x80" %>
          </td>
          <td>
            <%= link_to edit_admin_program_path(program) do %>
              <%= program.title %>
            <% end %>
          </td>
          <td>
            <%= program.category.name %>
          </td>
          <td>
            <%= program.start_time.strftime("%Y/%m/%d %H:%M") %>
          </td>
          <td>
            <%= program.created_at.strftime("%Y/%m/%d") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-end mb-1">
    ｜全 <%= @total_programs_count %> 件｜
    <%= paginate @programs, param_name: 'programs_page' %>
  </div>

app/views/admin/programs/new.html.erb
<h1>講座新規作成</h1>
<div class="mb-3 mr-3 text-right">
  <%= link_to '一覧へ戻る', admin_programs_path, class: "btn btn-secondary" %>
</div>

<% submit_label = "作成" %>
<%= render 'form', program: @program, submit_label: submit_label %>