config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'public/users/registrations',
   sessions: 'public/users/sessions'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :password], controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'inquiries#index'
    resources :users, only: [:index, :show, :edit, :update, :withdraw]
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :inquiries, only: [:index, :show, :update]
    resources :groups, only: [:index, :show, :destroy]
    resources :programs, except: :show
    resources :categories, except: :show
    get '/searches' => 'searches#search', as: "searches"
  end

  scope module: :public do
    devise_scope :user do
      post 'guest_login', to: 'users/sessions#guest_login'
    end
    resources :users, only: [:edit, :update, :show]
    get '/mypage' => 'users#mypage', as: "mypage"
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts do
      resources :comments, only: [:create, :show, :destroy]
    end
    resources :inquiries, only: [:new, :create]
    get 'inquiries/thanks' => 'inquiries#thanks', as: "thanks"
    resources :groups, except: :destroy do
      resource :user_group_combinations, only: [:create, :destroy]
    end
    resources :user_group_combinations, only: [:update]
    resources :programs, only: [:index, :show]
    get '/search' => 'searches#search', as: "search"
  end

  root to: "homes#home"
  get '/about' => 'homes#about', as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :programs, dependent: :destroy

  validates :name, presence: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'admin'
  
  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    existing_category = Category.find_by(name: category_params[:name])
    if existing_category
      flash.now[:danger] = "同じカテゴリー名が既に存在します"
      @categories = Category.all
      render :index
    else
      if @category.save
        flash[:notice] = "カテゴリーを登録しました"
        redirect_to admin_categories_path
      else
        flash.now[:danger] = "カテゴリーの登録に失敗しました"
        @categories = Category.all
        render :index
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "変更を保存しました"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = "変更の保存に失敗しました"
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:notice] = "削除しました"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_categories_index.html.erb
<div class="col-lg-9">
  <h4>カテゴリー一覧</h4>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>カテゴリー名</th>
        <th>登録日</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
    <% categories.each do |category| %>
      <tr>
        <td>
          <%= link_to edit_admin_category_path(category) do %>
            <%= category.name %>
          <% end %>
        </td>
        <td>
          <%= category.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= link_to '削除', admin_category_path(category), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-dark" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/edit.html.erb
<h1>カテゴリー</h1>

  <div class="row">
    <div class="col-lg-3 mb-3">
      <h4>カテゴリー編集</h4>
        <%= form_with model: [:admin, @category] do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <%= f.label :name, "カテゴリー名" %>
          <%= f.text_field :name %>

          <%= f.submit '変更を保存', class: "btn btn-secondary mt-lg-3" %>
        <% end %>
        <%= link_to '戻る', admin_categories_path, class: "btn btn-secondary mt-lg-3" %>
    </div>

    <%= render 'categories_index', categories: @categories %>
  </div>

app/views/admin/categories/index.html.erb
<h1 class="mb-3">カテゴリー</h1>

  <div class="row">
    <div class="col-lg-3 mb-3">
      <h4>カテゴリー新規登録</h4>
        <%= form_with model: [:admin, @category] do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <%= f.label :name, "カテゴリー名" %><br>
          <%= f.text_field :name %>

          <%= f.submit ' 登録 ', class: "btn btn-secondary mt-lg-3" %>
        <% end %>
    </div>

    <%= render 'categories_index', categories: @categories %>
  </div>