config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'public/users/registrations',
   sessions: 'public/users/sessions'
  }
  devise_for :admins, path: 'admin', skip: [:registrations, :password], controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'inquiries#index'
    resources :users, only: [:index, :show, :edit, :update, :withdraw]
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
    resources :inquiries, only: [:index, :show, :update]
    resources :groups, only: [:index, :show, :destroy]
    resources :programs, except: :show
    resources :categories, except: :show
    get '/searches' => 'searches#search', as: "searches"
  end

  scope module: :public do
    devise_scope :user do
      post 'guest_login', to: 'users/sessions#guest_login'
    end
    resources :users, only: [:edit, :update, :show]
    get '/mypage' => 'users#mypage', as: "mypage"
    patch 'users/:id/withdraw' => 'users#withdraw', as: "withdraw_user"
    resources :posts do
      resources :comments, only: [:create, :show, :destroy]
    end
    resources :inquiries, only: [:new, :create]
    get 'inquiries/thanks' => 'inquiries#thanks', as: "thanks"
    resources :groups, except: :destroy do
      resource :user_group_combinations, only: [:create, :destroy]
    end
    resources :user_group_combinations, only: [:update]
    resources :programs, only: [:index, :show]
    get '/search' => 'searches#search', as: "search"
  end

  root to: "homes#home"
  get '/about' => 'homes#about', as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :user_group_combinations, dependent: :destroy
  has_many :join_groups, through: :user_group_combinations, source: :group
  has_many :participating_user_group_combinations, -> { where( status: 'is_participating' ) }, class_name: 'UserGroupCombination'
  has_many :participating_join_groups, through: :participating_user_group_combinations, source: :group
  has_many :owner_groups, class_name: "Group", foreign_key: :owner_id

  validates :name, length: { minimum: 2, maximum: 20}, uniqueness: true, presence: true
  validates :email, presence: true

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name Like ?', content + '%')
    elsif method == 'backword'
      User.where('name Like ?', '%' + content)
    else
      User.where('name Like ?', '%' + content + '%')
    end
  end

  def join_group(group)
    user_group_combination = self.user_group_combinations.find_or_create_by(group: group)
    if user_group_combination.status == 'is_rejected'
      user_group_combination.update(status: 'is_pending')
    end
  end

  def reject_group(group)
    self.user_group_combinations.find_by(group: group)&.destroy
  end

  def join_group?(group)
    self.join_groups.include?(group)
  end

  GUEST_USER_EMAIL = "guest@test.com"

  def self.guest
    user = self.find_or_initialize_by(email: GUEST_USER_EMAIL)
    if user.new_record?
      user.assign_attributes(
        password: SecureRandom.hex(6),
        name: "ゲスト"
      )
    end
    user.save
    user
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'

  def index
    @users = User.page(params[:users_page])
    @total_users_count = User.all.count
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
    @total_posts_count = @user.posts.count
    @comments = @user.comments.page(params[:page])
    @total_comments_count = @user.comments.count
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更を保存しました"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = "変更の保存に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def mypage
  end

  def edit
  end

  def update
  end

  def show
  end

  def withdraw
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_index.html.erb
<div class="d-flex justify-content-end mb-1">
  <%= paginate users, param_name: 'users_page' %>
</div>
<table class="table table-hover">
  <thead>
    <tr style="background-color: rgba(165, 143, 134, 0.2);">
      <th>ユーザー名</th>
      <th>ユーザーステータス</th>
      <th>登録日</th>
      <th>更新日</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to admin_user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td>
          <%= user.is_active ? "有効" : "無効" %>
        </td>
        <td>
          <%= user.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= user.updated_at.strftime('%Y/%m/%d') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-end mt-1">
  <%= paginate users, param_name: 'users_page' %>
</div>

app/views/admin/users/edit.html.erb
<h1>ユーザー編集</h1>

<div class="row">
  <div class="col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
    <div class="card">
      <div class="card-body">
        <h2 class="d-flex justify-content-center">ユーザー情報の編集</h2>
          <%= form_with model: [:admin, @user] do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
              <label for="user_name">ユーザーネーム</label>
              <%= f.text_field :name, class: "form-control user_name" %>
            </div>
            <div class="form-group">
              <label for="user_email">メールアドレス</label>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control user_email" %>
            </div>
            <div class="form-group">
              <label for="is_active">ユーザーステータス</label>
              <%= f.select :is_active, options_for_select([["有効", true], ["無効", false]], @user.is_active), class: "form-control status" %>
            </div>
            <div class="form-group">
              <%= f.submit '変更を保存する', class: "btn btn-secondary btn-block" %>
            </div>
          <% end %>
          <%= link_to '戻る', admin_user_path(@user), class: "btn btn-secondary btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>
  <div class="d-flex justify-content-end mb-1">
    ｜全 <%= @total_users_count %> 件｜
    <%= paginate @users, param_name: 'users_page' %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr style="background-color: rgba(165, 143, 134, 0.2);">
        <th>ユーザー名</th>
        <th>ユーザーステータス</th>
        <th>登録日</th>
        <th>更新日</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to admin_user_path(user) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td>
            <%= user.is_active ? "有効" : "無効" %>
          </td>
          <td>
            <%= user.created_at.strftime('%Y/%m/%d') %>
          </td>
          <td>
            <%= user.updated_at.strftime('%Y/%m/%d') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-end mt-1">
    <%= paginate @users, param_name: 'users_page' %>
  </div>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>
<div class="text-right mb-3">
  <%= link_to '一覧に戻る', admin_users_path, class: "btn btn-secondary" %>
</div>
<div class="row">
  <div class="col-lg-4 mb-3">
    <p class="py-3 pl-1" style="background-color: rgba(165, 143, 134, 0.2);"><strong>ユーザー情報</strong></p>
    <p>
      ユーザー名：
      <%= @user.name %>
    </p>
    <p class="text-truncate">
      メールアドレス：
      <%= @user.email %>
    </p>
    <p>
      ユーザーステータス：
      <%= @user.is_active ? "有効" : "無効" %>
    </p>
    <p>
      登録日：
      <%= @user.created_at.strftime("%Y/%m/%d") %>
    </p>
    <p>
      更新日：
      <%= @user.updated_at.strftime("%Y/%m/%d") %>
    </p>
    <div class="text-right">
      <%= link_to '編集', edit_admin_user_path(@user), class: "btn btn-secondary" %>
    </div>
  </div>
  <div class="col-lg-4 mb-3">
    <p class="py-3 pl-1" style="background-color: rgba(165, 143, 134, 0.2);">
      <strong>投稿</strong>
      （<%= @total_posts_count %> 件）
    </p>
    <% @posts.each do |post| %>
      <%= link_to admin_post_path(post) do %>
        <div class="list-group-item list-group-item-action">
          <p>
            タイトル：
            <%= post.title %>
          </p>
          <p class="text-truncate">
            内容：
            <%= post.body %>
          </p>
        </div>
      <% end %>
    <% end %>
    <div class="mt-1">
      <%= paginate @posts %>
    </div>
  </div>
  <div class="col-lg-4 mb-3">
    <p class="py-3 pl-1" style="background-color: rgba(165, 143, 134, 0.2);">
      <strong>コメント</strong>
      （<%= @total_comments_count %> 件）
    </p>
    <% @comments.each do |comment| %>
      <%= link_to admin_comment_path(comment) do %>
        <div class="list-group-item list-group-item-action text-truncate">
          <%= comment.body %>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-3 offset-9 mt-1">
          <%= paginate @comments %>
        </div>
      </div>
    </div>
  </div>
</div>